export const THEME_COLORS = [
  'indigo', 'teal', 'emerald', 'rose', 'amber', 'sky', 'violet', 'orange', 'pink', 'slate'
] as const;

export type ThemeColor = typeof THEME_COLORS[number];

export const getThemeClasses = (color: string) => {
  const colors: Record<string, any> = {
    teal: {
      bg: 'bg-teal-600',
      text: 'text-teal-600',
      border: 'border-teal-600',
      hoverBg: 'hover:bg-teal-700',
      hoverText: 'hover:text-teal-600',
      hoverBorder: 'hover:border-teal-300',
      lightBg: 'bg-teal-50',
      lightText: 'text-teal-600',
      lightBorder: 'border-teal-100',
      groupHoverText: 'group-hover:text-teal-600',
      ring: 'focus:ring-teal-500/20',
      shadow: 'shadow-teal-200',
      borderLight: 'border-teal-100',
      hoverLightBg: 'hover:bg-teal-50',
      focusBorder: 'focus:border-teal-500',
      ringStatic: 'ring-teal-500',
      borderStatic: 'border-teal-200'
    },
    emerald: {
      bg: 'bg-emerald-600',
      text: 'text-emerald-600',
      border: 'border-emerald-600',
      hoverBg: 'hover:bg-emerald-700',
      hoverText: 'hover:text-emerald-600',
      hoverBorder: 'hover:border-emerald-300',
      lightBg: 'bg-emerald-50',
      lightText: 'text-emerald-600',
      lightBorder: 'border-emerald-100',
      groupHoverText: 'group-hover:text-emerald-600',
      ring: 'focus:ring-emerald-500/20',
      shadow: 'shadow-emerald-200',
      borderLight: 'border-emerald-100',
      hoverLightBg: 'hover:bg-emerald-50',
      focusBorder: 'focus:border-emerald-500',
      ringStatic: 'ring-emerald-500',
      borderStatic: 'border-emerald-200'
    },
    rose: {
      bg: 'bg-rose-600',
      text: 'text-rose-600',
      border: 'border-rose-600',
      hoverBg: 'hover:bg-rose-700',
      hoverText: 'hover:text-rose-600',
      hoverBorder: 'hover:border-rose-300',
      lightBg: 'bg-rose-50',
      lightText: 'text-rose-600',
      lightBorder: 'border-rose-100',
      groupHoverText: 'group-hover:text-rose-600',
      ring: 'focus:ring-rose-500/20',
      shadow: 'shadow-rose-200',
      borderLight: 'border-rose-100',
      hoverLightBg: 'hover:bg-rose-50',
      focusBorder: 'focus:border-rose-500',
      ringStatic: 'ring-rose-500',
      borderStatic: 'border-rose-200'
    },
    amber: {
      bg: 'bg-amber-600',
      text: 'text-amber-600',
      border: 'border-amber-600',
      hoverBg: 'hover:bg-amber-700',
      hoverText: 'hover:text-amber-600',
      hoverBorder: 'hover:border-amber-300',
      lightBg: 'bg-amber-50',
      lightText: 'text-amber-600',
      lightBorder: 'border-amber-100',
      groupHoverText: 'group-hover:text-amber-600',
      ring: 'focus:ring-amber-500/20',
      shadow: 'shadow-amber-200',
      borderLight: 'border-amber-100',
      hoverLightBg: 'hover:bg-amber-50',
      focusBorder: 'focus:border-amber-500',
      ringStatic: 'ring-amber-500',
      borderStatic: 'border-amber-200'
    },
    sky: {
      bg: 'bg-sky-600',
      text: 'text-sky-600',
      border: 'border-sky-600',
      hoverBg: 'hover:bg-sky-700',
      hoverText: 'hover:text-sky-600',
      hoverBorder: 'hover:border-sky-300',
      lightBg: 'bg-sky-50',
      lightText: 'text-sky-600',
      lightBorder: 'border-sky-100',
      groupHoverText: 'group-hover:text-sky-600',
      ring: 'focus:ring-sky-500/20',
      shadow: 'shadow-sky-200',
      borderLight: 'border-sky-100',
      hoverLightBg: 'hover:bg-sky-50',
      focusBorder: 'focus:border-sky-500',
      ringStatic: 'ring-sky-500',
      borderStatic: 'border-sky-200'
    },
    violet: {
      bg: 'bg-violet-600',
      text: 'text-violet-600',
      border: 'border-violet-600',
      hoverBg: 'hover:bg-violet-700',
      hoverText: 'hover:text-violet-600',
      hoverBorder: 'hover:border-violet-300',
      lightBg: 'bg-violet-50',
      lightText: 'text-violet-600',
      lightBorder: 'border-violet-100',
      groupHoverText: 'group-hover:text-violet-600',
      ring: 'focus:ring-violet-500/20',
      shadow: 'shadow-violet-200',
      borderLight: 'border-violet-100',
      hoverLightBg: 'hover:bg-violet-50',
      focusBorder: 'focus:border-violet-500',
      ringStatic: 'ring-violet-500',
      borderStatic: 'border-violet-200'
    },
    orange: {
      bg: 'bg-orange-600',
      text: 'text-orange-600',
      border: 'border-orange-600',
      hoverBg: 'hover:bg-orange-700',
      hoverText: 'hover:text-orange-600',
      hoverBorder: 'hover:border-orange-300',
      lightBg: 'bg-orange-50',
      lightText: 'text-orange-600',
      lightBorder: 'border-orange-100',
      groupHoverText: 'group-hover:text-orange-600',
      ring: 'focus:ring-orange-500/20',
      shadow: 'shadow-orange-200',
      borderLight: 'border-orange-100',
      hoverLightBg: 'hover:bg-orange-50',
      focusBorder: 'focus:border-orange-500',
      ringStatic: 'ring-orange-500',
      borderStatic: 'border-orange-200'
    },
    pink: {
      bg: 'bg-pink-600',
      text: 'text-pink-600',
      border: 'border-pink-600',
      hoverBg: 'hover:bg-pink-700',
      hoverText: 'hover:text-pink-600',
      hoverBorder: 'hover:border-pink-300',
      lightBg: 'bg-pink-50',
      lightText: 'text-pink-600',
      lightBorder: 'border-pink-100',
      groupHoverText: 'group-hover:text-pink-600',
      ring: 'focus:ring-pink-500/20',
      shadow: 'shadow-pink-200',
      borderLight: 'border-pink-100',
      hoverLightBg: 'hover:bg-pink-50',
      focusBorder: 'focus:border-pink-500',
      ringStatic: 'ring-pink-500',
      borderStatic: 'border-pink-200'
    },
    slate: {
      bg: 'bg-slate-600',
      text: 'text-slate-600',
      border: 'border-slate-600',
      hoverBg: 'hover:bg-slate-700',
      hoverText: 'hover:text-slate-600',
      hoverBorder: 'hover:border-slate-300',
      lightBg: 'bg-slate-50',
      lightText: 'text-slate-600',
      lightBorder: 'border-slate-100',
      groupHoverText: 'group-hover:text-slate-600',
      ring: 'focus:ring-slate-500/20',
      shadow: 'shadow-slate-200',
      borderLight: 'border-slate-100',
      hoverLightBg: 'hover:bg-slate-50',
      focusBorder: 'focus:border-slate-500',
      ringStatic: 'ring-slate-500',
      borderStatic: 'border-slate-200'
    },
    indigo: {
      bg: 'bg-indigo-600',
      text: 'text-indigo-600',
      border: 'border-indigo-600',
      hoverBg: 'hover:bg-indigo-700',
      hoverText: 'hover:text-indigo-600',
      hoverBorder: 'hover:border-indigo-300',
      lightBg: 'bg-indigo-50',
      lightText: 'text-indigo-600',
      lightBorder: 'border-indigo-100',
      groupHoverText: 'group-hover:text-indigo-600',
      ring: 'focus:ring-indigo-500/20',
      shadow: 'shadow-indigo-200',
      borderLight: 'border-indigo-100',
      hoverLightBg: 'hover:bg-indigo-50',
      focusBorder: 'focus:border-indigo-500',
      ringStatic: 'ring-indigo-500',
      borderStatic: 'border-indigo-200'
    }
  };

  return colors[color] || colors.indigo;
};

export const PROJECT_STATE_COLORS: Record<string, { bg: string, text: string, border: string, ring?: string }> = {
  'On-Track':   { bg: 'bg-emerald-50',  text: 'text-emerald-700', border: 'border-emerald-100' },
  'Delayed':    { bg: 'bg-red-50',      text: 'text-red-600',     border: 'border-red-100',    ring: 'ring-red-100' },
  'Suspended':  { bg: 'bg-slate-800',   text: 'text-white',       border: 'border-slate-800',  ring: 'ring-slate-200' },
  'Signed Off': { bg: 'bg-amber-50',    text: 'text-amber-700',   border: 'border-amber-200' },
  'Billed':     { bg: 'bg-blue-50',     text: 'text-blue-600',    border: 'border-blue-100' },
  'Closed':     { bg: 'bg-emerald-600', text: 'text-white',       border: 'border-emerald-700' },
};

export const PRIORITY_COLORS: Record<string, { bg: string, text: string, border: string }> = {
  'P1': { bg: 'bg-red-50', text: 'text-red-600', border: 'border-red-100' },
  'P2': { bg: 'bg-amber-50', text: 'text-amber-600', border: 'border-amber-100' },
  'P3': { bg: 'bg-sky-50', text: 'text-sky-600', border: 'border-sky-100' },
};
