import { format, subDays } from 'date-fns';
import { Project, Role, RevenueTrend, AuditLog, WeightHistory, User, AppConfig } from './types';

const now = new Date();

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    clientName: 'Global Trust Bank',
    packageName: 'Digital Transformation Program',
    services: ['Mobile', 'CBA', 'USSD'],
    productLines: ['Bankone', 'Channels'],
    assignedPM: 'Sarah Jenkins',
    startDate: format(subDays(now, 60), 'yyyy-MM-dd'),
    expectedDuration: 65,
    expectedCompletionDate: format(subDays(now, 5), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, 5), 'yyyy-MM-dd'),
    value: 120000,
    currency: 'USD',
    state: 'On-Track',
    createdAt: format(subDays(now, 65), 'yyyy-MM-dd'),
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Completed', completionDate: format(subDays(now, 55), 'yyyy-MM-dd') },
      { id: 'Planning', name: 'Planning', status: 'Completed', completionDate: format(subDays(now, 45), 'yyyy-MM-dd') },
      { id: 'Execution', name: 'Execution', status: 'In Progress' },
      { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'Mobile': 'Closed',
      'CBA': 'In Progress',
      'USSD': 'Not Started'
    },
    pidSignedOffDate: format(subDays(now, 60), 'yyyy-MM-dd'),
    comments: [
      { id: 'c1', author: 'Sarah Jenkins', text: 'Development is ahead of schedule. UAT set to begin Monday.', timestamp: format(subDays(now, 2), 'yyyy-MM-dd HH:mm') }
    ],
    risks: [],
    priority: 'P1',
    updatedAt: format(subDays(now, 1), 'yyyy-MM-dd'),
    activities: [
      { id: 'a1', type: 'StateChange', user: 'Sarah Jenkins', description: 'Moved to On-Track', timestamp: format(subDays(now, 55), 'yyyy-MM-dd HH:mm') }
    ],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '2',
    clientName: 'Apex Microfinance',
    packageName: 'Digital Banking Program',
    services: ['Agency', 'Merchant Banking'],
    productLines: ['Bankone'],
    assignedPM: 'Michael Chen',
    startDate: format(subDays(now, 30), 'yyyy-MM-dd'),
    expectedDuration: 45,
    expectedCompletionDate: format(subDays(now, -15), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, -15), 'yyyy-MM-dd'),
    value: 45000000,
    currency: 'NGN',
    state: 'Delayed',
    createdAt: format(subDays(now, 45), 'yyyy-MM-dd'),
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Completed', completionDate: format(subDays(now, 25), 'yyyy-MM-dd') },
      { id: 'Planning', name: 'Planning', status: 'In Progress' },
      { id: 'Execution', name: 'Execution', status: 'Locked' },
      { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'Agency': 'Not Started',
      'Merchant Banking': 'Not Started'
    },
    pidSignedOffDate: format(subDays(now, 28), 'yyyy-MM-dd'),
    comments: [],
    risks: [
      { id: 'r2', description: 'Server infrastructure not ready', impact: 'High', status: 'Open', createdAt: format(subDays(now, 2), 'yyyy-MM-dd') }
    ],
    priority: 'P2',
    updatedAt: format(subDays(now, 20), 'yyyy-MM-dd'),
    activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '3',
    clientName: 'Zenith Connect',
    packageName: 'Digital Uplift Program',
    services: ['USSD', 'Mobile', 'APIs'],
    productLines: ['Channels'],
    assignedPM: 'Sarah Jenkins',
    startDate: format(subDays(now, 60), 'yyyy-MM-dd'),
    expectedDuration: 55,
    expectedCompletionDate: format(subDays(now, 5), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, 5), 'yyyy-MM-dd'),
    value: 85000,
    currency: 'USD',
    state: 'On-Track',
    createdAt: format(subDays(now, 65), 'yyyy-MM-dd'),
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Pending' },
      { id: 'Planning', name: 'Planning', status: 'Locked' },
      { id: 'Execution', name: 'Execution', status: 'Locked' },
      { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'USSD': 'Not Started',
      'Mobile': 'Not Started',
      'APIs': 'Not Started'
    },
    comments: [],
    risks: [],
    priority: 'P1',
    updatedAt: format(subDays(now, 3), 'yyyy-MM-dd'),
    activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '4',
    clientName: 'Stellar Fin',
    packageName: 'CBA Program',
    services: ['Web'],
    productLines: ['Paypoint'],
    assignedPM: 'David Okoro',
    startDate: format(subDays(now, 15), 'yyyy-MM-dd'),
    expectedDuration: 15,
    expectedCompletionDate: format(subDays(now, -3), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, -3), 'yyyy-MM-dd'),
    value: 20000,
    currency: 'USD',
    state: 'On-Track',
    createdAt: format(subDays(now, 20), 'yyyy-MM-dd'),
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Pending' },
      { id: 'Planning', name: 'Planning', status: 'Locked' },
      { id: 'Execution', name: 'Execution', status: 'Locked' },
      { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'Web': 'Not Started'
    },
    comments: [],
    risks: [],
    priority: 'P3',
    updatedAt: format(subDays(now, 5), 'yyyy-MM-dd'),
    activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '5',
    clientName: 'Eco Bank',
    packageName: 'Retail Banking Program',
    services: ['Mobile'],
    productLines: ['Channels'],
    assignedPM: 'Michael Chen',
    startDate: format(subDays(now, 10), 'yyyy-MM-dd'),
    expectedDuration: 25,
    expectedCompletionDate: format(subDays(now, -15), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, -15), 'yyyy-MM-dd'),
    value: 15000,
    currency: 'USD',
    state: 'Suspended',
    createdAt: format(subDays(now, 15), 'yyyy-MM-dd'),
    phases: [
       { id: 'Initiation', name: 'Initiation', status: 'Completed' },
       { id: 'Planning', name: 'Planning', status: 'In Progress' },
       { id: 'Execution', name: 'Execution', status: 'Locked' },
       { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'Mobile': 'Not Started'
    },
    comments: [],
    risks: [],
    priority: 'P2',
    updatedAt: format(subDays(now, 2), 'yyyy-MM-dd'),
    activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '6',
    clientName: 'Recova Plus',
    packageName: 'Lending as a Service',
    services: ['USSD'],
    productLines: ['Recova'],
    assignedPM: 'David Okoro',
    startDate: format(subDays(now, 45), 'yyyy-MM-dd'),
    expectedDuration: 30,
    expectedCompletionDate: format(subDays(now, 15), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, 15), 'yyyy-MM-dd'),
    value: 35000000,
    currency: 'NGN',
    state: 'On-Track',
    createdAt: format(subDays(now, 50), 'yyyy-MM-dd'),
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Completed' },
      { id: 'Planning', name: 'Planning', status: 'Completed' },
      { id: 'Execution', name: 'Execution', status: 'In Progress' },
      { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'USSD': 'In Progress'
    },
    comments: [],
    risks: [],
    priority: 'P2',
    updatedAt: format(subDays(now, 10), 'yyyy-MM-dd'),
    activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '7',
    clientName: 'Prime Bank',
    packageName: 'Distributed Banking Program',
    services: ['Lending'],
    productLines: ['Bankone'],
    assignedPM: 'Sarah Jenkins',
    startDate: format(subDays(now, 100), 'yyyy-MM-dd'),
    expectedDuration: 90,
    expectedCompletionDate: format(subDays(now, 10), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, 10), 'yyyy-MM-dd'),
    value: 200000000,
    currency: 'NGN',
    state: 'Signed Off',
    createdAt: format(subDays(now, 105), 'yyyy-MM-dd'),
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Completed' },
      { id: 'Planning', name: 'Planning', status: 'Completed' },
      { id: 'Execution', name: 'Execution', status: 'Completed' },
      { id: 'Closure', name: 'Closure', status: 'Completed' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'Lending': 'Closed'
    },
    comments: [],
    risks: [],
    priority: 'P1',
    updatedAt: format(subDays(now, 5), 'yyyy-MM-dd'),
    activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '8',
    clientName: 'Rapid Pay',
    packageName: 'Cluster Program',
    services: ['API'],
    productLines: ['Paypoint'],
    assignedPM: 'Michael Chen',
    startDate: format(subDays(now, 15), 'yyyy-MM-dd'),
    expectedDuration: 20,
    expectedCompletionDate: format(subDays(now, -5), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, -5), 'yyyy-MM-dd'),
    value: 15000000,
    currency: 'NGN',
    state: 'Signed Off',
    createdAt: format(subDays(now, 20), 'yyyy-MM-dd'),
    signedOffAt: format(subDays(now, 1), 'yyyy-MM-dd'),
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Completed' },
      { id: 'Planning', name: 'Planning', status: 'Completed' },
      { id: 'Execution', name: 'Execution', status: 'Completed' },
      { id: 'Closure', name: 'Closure', status: 'Completed' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'API': 'Closed'
    },
    comments: [],
    risks: [],
    priority: 'P3',
    updatedAt: format(subDays(now, 1), 'yyyy-MM-dd'),
    activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '9',
    clientName: 'Legacy Corp',
    packageName: 'CBA Program',
    services: ['CBA'],
    productLines: ['Bankone'],
    assignedPM: 'Abisoye Adeyemi',
    startDate: format(subDays(now, 120), 'yyyy-MM-dd'),
    expectedDuration: 100,
    expectedCompletionDate: format(subDays(now, 20), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, 20), 'yyyy-MM-dd'),
    value: 50000,
    currency: 'NGN',
    state: 'On-Track',
    createdAt: format(subDays(now, 125), 'yyyy-MM-dd'),
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Completed' },
      { id: 'Planning', name: 'Planning', status: 'Completed' },
      { id: 'Execution', name: 'Execution', status: 'In Progress' },
      { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'CBA': 'In Progress'
    },
    comments: [],
    risks: [],
    priority: 'P2',
    updatedAt: format(subDays(now, 50), 'yyyy-MM-dd'),
    activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '10',
    clientName: 'Old School Fin',
    packageName: 'Digital Uplift Program',
    services: ['Mobile'],
    productLines: ['Channels'],
    assignedPM: 'Abisoye Adeyemi',
    startDate: format(subDays(now, 150), 'yyyy-MM-dd'),
    expectedDuration: 130,
    expectedCompletionDate: format(subDays(now, 20), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, 20), 'yyyy-MM-dd'),
    value: 30000,
    currency: 'USD',
    state: 'Delayed',
    createdAt: format(subDays(now, 155), 'yyyy-MM-dd'),
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Pending' },
      { id: 'Planning', name: 'Planning', status: 'Locked' },
      { id: 'Execution', name: 'Execution', status: 'Locked' },
      { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'Mobile': 'Not Started'
    },
    comments: [],
    risks: [],
    priority: 'P1',
    updatedAt: format(subDays(now, 60), 'yyyy-MM-dd'),
    activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '11',
    clientName: 'Future Bank',
    packageName: 'Digital Banking Program',
    services: ['Cloud', 'API'],
    productLines: ['Bankone'],
    assignedPM: 'Sarah Jenkins',
    startDate: format(subDays(now, 20), 'yyyy-MM-dd'),
    expectedDuration: 40,
    expectedCompletionDate: format(subDays(now, -20), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, -20), 'yyyy-MM-dd'),
    value: 45000000,
    currency: 'NGN',
    state: 'Delayed',
    createdAt: format(subDays(now, 25), 'yyyy-MM-dd'),
    updatedAt: format(subDays(now, 10), 'yyyy-MM-dd'),
    priority: 'P1',
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Pending' },
      { id: 'Planning', name: 'Planning', status: 'Locked' },
      { id: 'Execution', name: 'Execution', status: 'Locked' },
      { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'Cloud': 'Not Started',
      'API': 'Not Started'
    },
    comments: [], risks: [], activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  },
  {
    id: '12',
    clientName: 'Amber Ventures',
    packageName: 'Retail Banking Program',
    services: ['Advisory'],
    productLines: ['Channels'],
    assignedPM: 'David Okoro',
    startDate: format(subDays(now, 20), 'yyyy-MM-dd'),
    expectedDuration: 35,
    expectedCompletionDate: format(subDays(now, -15), 'yyyy-MM-dd'),
    currentCompletionDate: format(subDays(now, -15), 'yyyy-MM-dd'),
    value: 1200000,
    currency: 'NGN',
    state: 'Delayed',
    createdAt: format(subDays(now, 25), 'yyyy-MM-dd'),
    updatedAt: format(subDays(now, 5), 'yyyy-MM-dd'),
    priority: 'P2',
    phases: [
      { id: 'Initiation', name: 'Initiation', status: 'Pending' },
      { id: 'Planning', name: 'Planning', status: 'Locked' },
      { id: 'Execution', name: 'Execution', status: 'Locked' },
      { id: 'Closure', name: 'Closure', status: 'Locked' },
    ],
    phaseWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceStates: {
      'Advisory': 'Not Started'
    },
    comments: [], risks: [], activities: [],
    rebaselineRequests: [],
    suspensionCycles: []
  }
];

export const MOCK_REVENUE_TREND: RevenueTrend[] = [
  { month: 'Apr 2025', intakeNGN: 45000000, achievedNGN: 30000000, intakeUSD: 20000, achievedUSD: 15000 },
  { month: 'May 2025', intakeNGN: 55000000, achievedNGN: 40000000, intakeUSD: 25000, achievedUSD: 18000 },
  { month: 'Jun 2025', intakeNGN: 65000000, achievedNGN: 45000000, intakeUSD: 30000, achievedUSD: 20000 },
  { month: 'Jul 2025', intakeNGN: 75000000, achievedNGN: 50000000, intakeUSD: 35000, achievedUSD: 25000 },
  { month: 'Aug 2025', intakeNGN: 85000000, achievedNGN: 55000000, intakeUSD: 40000, achievedUSD: 30000 },
  { month: 'Sep 2025', intakeNGN: 45000000, achievedNGN: 60000000, intakeUSD: 20000, achievedUSD: 28000 },
  { month: 'Oct 2025', intakeNGN: 65000000, achievedNGN: 65000000, intakeUSD: 30000, achievedUSD: 30000 },
  { month: 'Nov 2025', intakeNGN: 95000000, achievedNGN: 70000000, intakeUSD: 45000, achievedUSD: 35000 },
  { month: 'Dec 2025', intakeNGN: 80000000, achievedNGN: 55000000, intakeUSD: 35000, achievedUSD: 30000 },
  { month: 'Jan 2026', intakeNGN: 45000000, achievedNGN: 60000000, intakeUSD: 20000, achievedUSD: 28000 },
  { month: 'Feb 2026', intakeNGN: 60000000, achievedNGN: 60000000, intakeUSD: 25000, achievedUSD: 25000 },
  { month: 'Mar 2026', intakeNGN: 70000000, achievedNGN: 50000000, intakeUSD: 30000, achievedUSD: 20000 },
];

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Sarah Jenkins', email: 'sarah.j@qore.com', role: 'PM', status: 'Active', avatar: 'SJ' },
  { id: 'u2', name: 'Michael Chen', email: 'm.chen@qore.com', role: 'PM', status: 'Active', avatar: 'MC' },
  { id: 'u3', name: 'David Okoro', email: 'd.okoro@qore.com', role: 'PM', status: 'Active', avatar: 'DO' },
  { id: 'u4', name: 'Admin User', email: 'admin@qore.com', role: 'Superadmin', status: 'Active', avatar: 'AU' },
  { id: 'u5', name: 'Finance Lead', email: 'finance@qore.com', role: 'Finance', status: 'Active', avatar: 'FL' },
  { id: 'u6', name: 'Exec Director', email: 'exec@qore.com', role: 'Executive', status: 'Active', avatar: 'ED' },
  { id: 'u7', name: 'James Wilson', email: 'j.wilson@qore.com', role: 'Manager', status: 'Active', avatar: 'JW' },
  { id: 'u8', name: 'Abisoye Adeyemi', email: 'a.adeyemi@qore.com', role: 'PM', status: 'Inactive', avatar: 'AA', invitedAt: format(subDays(now, 100), 'yyyy-MM-dd HH:mm') },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  { id: 'l1', action: 'Project Created', user: 'Sarah Jenkins', details: 'Created project for Global Trust Bank', timestamp: format(subDays(now, 50), 'yyyy-MM-dd HH:mm'), category: 'Project' },
  { id: 'l2', action: 'Weight Updated', user: 'Admin User', details: 'Updated Digital Transformation Program weight from 1.0 to 1.2', timestamp: format(subDays(now, 5), 'yyyy-MM-dd HH:mm'), category: 'Config' },
  { id: 'l3', action: 'State Change', user: 'Michael Chen', details: 'Apex Microfinance moved to Delayed', timestamp: format(subDays(now, 2), 'yyyy-MM-dd HH:mm'), category: 'Project' },
];

export const INITIAL_CONFIG: AppConfig = {
    spiThresholds: { onTrack: 1.0, atRisk: 0.8 },
    atRiskThresholdDays: 7,
    staleThresholdDays: 14,
    currencies: [
      { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', isActive: true },
      { code: 'USD', symbol: '$', name: 'US Dollar', isActive: true },
    ],
    brand: {
      companyName: 'Qore PD',
      logoUrl: '',
      themeColor: 'teal'
    },
    projectLifecycleWeights: { initiation: 10, planning: 10, execution: 60, closure: 20 },
    serviceBaselines: [
      { id: 'sb1', name: 'CBA', baselineDays: 20 },
      { id: 'sb2', name: 'USSD', baselineDays: 5 },
      { id: 'sb3', name: 'Transfers', baselineDays: 10 },
      { id: 'sb4', name: 'Mobile', baselineDays: 15 },
      { id: 'sb5', name: 'Cards', baselineDays: 10 },
      { id: 'sb6', name: 'APIs', baselineDays: 10 },
      { id: 'sb7', name: 'CDR', baselineDays: 30 },
      { id: 'sb8', name: 'CAS', baselineDays: 20 },
      { id: 'sb9', name: 'Collections and Recovery', baselineDays: 25 },
      { id: 'sb10', name: 'Agency', baselineDays: 15 },
      { id: 'sb11', name: 'Merchant Banking', baselineDays: 15 },
    ],
    allowPostIntakeRevenueEdit: false,
    pmScorecardWeights: { deliveryRate: 0.4, avgSpi: 0.4, rebaselineRate: 0.2 },
    workloadThresholds: {
        P1: 3,
        P2: 5,
        P3: 8
    },
    maxImportRows: 500,
    hideImportGuide: false
};

export const MOCK_WEIGHT_HISTORY: WeightHistory[] = [
  { id: 'wh1', packageName: 'Cloud Core Migration', oldWeight: 1.0, newWeight: 1.2, updatedBy: 'Admin User', timestamp: format(subDays(now, 5), 'yyyy-MM-dd HH:mm') },
  { id: 'wh2', packageName: 'Digital Transformation Program', oldWeight: 1.5, newWeight: 1.8, updatedBy: 'Sarah Jenkins', timestamp: format(subDays(now, 10), 'yyyy-MM-dd HH:mm') },
];
